input_data: ../../data_preprocessing/training_data/modeling_input.txt

best_params:
  n_estimators: 1000
  max_depth: 12
  min_samples_split: 10
  min_samples_leaf: 10
  max_features: 0.5
  criterion: gini

chosen_threshold: 0.60
seed: 874216

